<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmA1ng6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmA1ng6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmA1ng6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmA1ng6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmA1ng6\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmA1ng6',
    'container.build_id' => '6b29fd74',
    'container.build_time' => 1583352495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmA1ng6');
