version: "3.7"

services:
    rota-service:
        depends_on:
          - rota-database
        build: rota-service
        volumes:
            - ./rota-service/rota:/var/www
        ports:
            - 81:80
        environment:
            DATABASE_URL: "mysql://root:root@rota-database/rota"
        command: composer install

    rota-database:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "rota"
